import { toAcaSelfVerifierMediaItems } from "./aca-self-verifiers";

export type PublicMediaItem = {
  id: string;
  title: string;
  alt: string | null;
  src: string;
  kind: string;
  section: string;
  category: string;
  order: number;
  isFeatured: boolean;
};

export const fallbackMediaItems: PublicMediaItem[] = [
  {
    id: "award-1",
    title: "iPhone & Certificate Award",
    alt: "BALITECH employee receiving iPhone and certificate award",
    src: "/awards/award-iphone-certificate.png",
    kind: "image",
    section: "awards",
    category: "Awards",
    order: 1,
    isFeatured: true,
  },
  {
    id: "award-honda",
    title: "Honda CG 125 Top Performer",
    alt: "BALITECH top performer Honda CG 125 motorcycle presentation",
    src: "/awards/award-honda-motorcycle-presentation.jpg",
    kind: "image",
    section: "awards",
    category: "Awards",
    order: 2,
    isFeatured: false,
  },
  {
    id: "award-emporio",
    title: "Top Performer Emporio Armani Gift",
    alt: "BALITECH top performer receiving Emporio Armani gift",
    src: "/awards/award-emporio-armani-gift.jpg",
    kind: "image",
    section: "awards",
    category: "Awards",
    order: 3,
    isFeatured: false,
  },
  {
    id: "award-honda-key",
    title: "Honda Key Presentation",
    alt: "BALITECH Honda key presentation for top performer",
    src: "/awards/award-honda-key-presentation.png",
    kind: "image",
    section: "awards",
    category: "Awards",
    order: 4,
    isFeatured: false,
  },
  {
    id: "award-certificate",
    title: "Certificate Ceremony",
    alt: "BALITECH certificate award ceremony",
    src: "/awards/award-certificate-ceremony.png",
    kind: "image",
    section: "awards",
    category: "Awards",
    order: 5,
    isFeatured: false,
  },
  {
    id: "award-honda-group",
    title: "Honda Award Group",
    alt: "BALITECH team Honda award group photo",
    src: "/awards/award-honda-key-group.png",
    kind: "image",
    section: "awards",
    category: "Awards",
    order: 6,
    isFeatured: false,
  },
  {
    id: "bonus-tommy",
    title: "Tommy Espinoza — Med Alert Bonus Achiever",
    alt: "Tommy Espinoza Med Alert Bonus Achiever — earned 166,500",
    src: "/awards/bonus-tommy-espinoza.png",
    kind: "image",
    section: "bonus-achievers",
    category: "Awards",
    order: 1,
    isFeatured: false,
  },
  {
    id: "bonus-ronnie",
    title: "Ronnie Adams — Med Alert Bonus Achiever",
    alt: "Ronnie Adams Med Alert Bonus Achiever — earned 251,500",
    src: "/awards/bonus-ronnie-adams.png",
    kind: "image",
    section: "bonus-achievers",
    category: "Awards",
    order: 2,
    isFeatured: false,
  },
  {
    id: "bonus-ken",
    title: "Ken Lee — Med Alert Bonus Achiever",
    alt: "Ken Lee Med Alert Bonus Achiever — earned 176,500",
    src: "/awards/bonus-ken-lee.png",
    kind: "image",
    section: "bonus-achievers",
    category: "Awards",
    order: 3,
    isFeatured: false,
  },
  {
    id: "promo-mohsin",
    title: "Mohsin Nazir — Verifier to Team Lead",
    alt: "Mohsin Nazir promoted from Verifier to Team Lead at BALITECH",
    src: "/awards/promotion-mohsin-nazir.png",
    kind: "image",
    section: "promotions",
    category: "Team",
    order: 1,
    isFeatured: false,
  },
  {
    id: "promo-shad",
    title: "Shad Azam — Verifier to Team Lead",
    alt: "Shad Azam promoted from Verifier to Team Lead at BALITECH",
    src: "/awards/promotion-shad-azam.png",
    kind: "image",
    section: "promotions",
    category: "Team",
    order: 2,
    isFeatured: false,
  },
  {
    id: "promo-haris",
    title: "Haris Zaheer — Associate Manager",
    alt: "Haris Zaheer promoted to Associate Manager at BALITECH",
    src: "/awards/promotion-haris-zaheer.png",
    kind: "image",
    section: "promotions",
    category: "Team",
    order: 3,
    isFeatured: false,
  },
  {
    id: "promo-zimmel",
    title: "Zimmel Shahid — Retention Manager",
    alt: "Zimmel Shahid promoted from Closer to Retention Manager on Med Alert Campaign",
    src: "/awards/promotion-zimmel-shahid.png",
    kind: "image",
    section: "promotions",
    category: "Team",
    order: 4,
    isFeatured: false,
  },
  {
    id: "workspace-1",
    title: "Main Office Floor",
    alt: "BALITECH office — main workspace and team floor",
    src: "/balitech_office/DSC03829.JPG",
    kind: "image",
    section: "workspace",
    category: "Office",
    order: 1,
    isFeatured: true,
  },
  {
    id: "workspace-2",
    title: "Operations Center",
    alt: "BALITECH office — operations and call center area",
    src: "/balitech_office/DSC03814.JPG",
    kind: "image",
    section: "workspace",
    category: "Office",
    order: 2,
    isFeatured: false,
  },
  {
    id: "workspace-3",
    title: "Team Workstations",
    alt: "BALITECH office — team workstations",
    src: "/balitech_office/DSC03811.JPG",
    kind: "image",
    section: "workspace",
    category: "Office",
    order: 3,
    isFeatured: false,
  },
  {
    id: "video-serena",
    title: "ACA Serena Breakfast",
    alt: "ACA Serena Breakfast event video",
    src: "/Serena%20Breakfast/ACA%20Serena%20Breakfast.mp4",
    kind: "video",
    section: "portrait-video",
    category: "Events",
    order: 1,
    isFeatured: false,
  },
  {
    id: "video-transition",
    title: "Transition Video",
    alt: "BALITECH transition video",
    src: "/transition%20video/Transition%20Video1.mp4",
    kind: "video",
    section: "portrait-video",
    category: "Events",
    order: 2,
    isFeatured: false,
  },
  {
    id: "video-independence",
    title: "Independence Day Celebration",
    alt: "Independence Day celebration video",
    src: "/independence%20video/Independence%20day%20celeberation.mp4",
    kind: "video",
    section: "portrait-video",
    category: "Events",
    order: 3,
    isFeatured: false,
  },
  {
    id: "video-new-year",
    title: "Balitech New Year",
    alt: "Balitech New Year celebration video",
    src: "/newyear/Balitech%20New%20Year.mp4",
    kind: "video",
    section: "featured-video",
    category: "Events",
    order: 1,
    isFeatured: true,
  },
  {
    id: "events-1",
    title: "Strategic Session",
    alt: "Strategic Session",
    src: "/gallery/gallery-event-1.jpg",
    kind: "image",
    section: "events",
    category: "Events",
    order: 1,
    isFeatured: true,
  },
  {
    id: "events-2",
    title: "Leadership Briefing",
    alt: "Leadership Briefing",
    src: "/gallery/gallery-team-group-night.png",
    kind: "image",
    section: "events",
    category: "Events",
    order: 2,
    isFeatured: false,
  },
  {
    id: "events-3",
    title: "Balitech Commercial Office",
    alt: "Balitech Commercial Office",
    src: "/gallery/gallery-event-3.png",
    kind: "image",
    section: "events",
    category: "Office",
    order: 3,
    isFeatured: false,
  },
  {
    id: "events-4",
    title: "Annual Celebrations",
    alt: "Annual Celebrations",
    src: "/gallery/gallery-event-4.jpg",
    kind: "image",
    section: "events",
    category: "Events",
    order: 4,
    isFeatured: false,
  },
  {
    id: "events-5",
    title: "Top Performers Recognition",
    alt: "Top Performers Recognition",
    src: "/gallery/gallery-event-5.png",
    kind: "image",
    section: "events",
    category: "Awards",
    order: 5,
    isFeatured: false,
  },
  {
    id: "gallery-1",
    title: "Annual Dinner 2025",
    alt: "Annual Dinner 2025",
    src: "/gallery/gallery-event-1.jpg",
    kind: "image",
    section: "gallery",
    category: "Events",
    order: 1,
    isFeatured: false,
  },
  {
    id: "gallery-2",
    title: "Employee Awards Night",
    alt: "Employee Awards Night",
    src: "/awards/award-certificate-ceremony.png",
    kind: "image",
    section: "gallery",
    category: "Awards",
    order: 2,
    isFeatured: false,
  },
  {
    id: "gallery-3",
    title: "Team Group Night",
    alt: "BALITECH team group photo at night",
    src: "/gallery/gallery-team-group-night.png",
    kind: "image",
    section: "gallery",
    category: "Team",
    order: 3,
    isFeatured: false,
  },
  {
    id: "gallery-4",
    title: "Annual Celebrations",
    alt: "Annual Celebrations",
    src: "/gallery/gallery-event-4.jpg",
    kind: "image",
    section: "gallery",
    category: "Events",
    order: 4,
    isFeatured: false,
  },
  {
    id: "gallery-5",
    title: "Top Performer Ceremony",
    alt: "Top Performer Ceremony",
    src: "/awards/award-honda-motorcycle-presentation.jpg",
    kind: "image",
    section: "gallery",
    category: "Awards",
    order: 5,
    isFeatured: false,
  },
  {
    id: "gallery-6",
    title: "Main Office Floor",
    alt: "Main Office Floor",
    src: "/balitech_office/DSC03829.JPG",
    kind: "image",
    section: "gallery",
    category: "Office",
    order: 6,
    isFeatured: false,
  },
  {
    id: "gallery-7",
    title: "Operations Center",
    alt: "Operations Center",
    src: "/balitech_office/DSC03814.JPG",
    kind: "image",
    section: "gallery",
    category: "Office",
    order: 7,
    isFeatured: false,
  },
  {
    id: "gallery-8",
    title: "Commercial Office Floor",
    alt: "Commercial Office Floor",
    src: "/gallery/gallery-office-workplace-1.jpg",
    kind: "image",
    section: "gallery",
    category: "Office",
    order: 8,
    isFeatured: false,
  },
  {
    id: "gallery-9",
    title: "Commercial Workspaces",
    alt: "Commercial Workspaces",
    src: "/gallery/gallery-office-workplace-2.jpg",
    kind: "image",
    section: "gallery",
    category: "Office",
    order: 9,
    isFeatured: false,
  },
  {
    id: "gallery-10",
    title: "Commercial Operations",
    alt: "Commercial Operations",
    src: "/gallery/gallery-office-workplace-3.jpg",
    kind: "image",
    section: "gallery",
    category: "Office",
    order: 10,
    isFeatured: false,
  },
  {
    id: "gallery-fruit-01",
    title: "Fruit Day — Summer Celebration",
    alt: "BALITECH Culture Day and Prize Distribution — team at summer celebration backdrop",
    src: "/baliCulture_Day/fruit-day/fruit-day-01.png",
    kind: "image",
    section: "gallery",
    category: "Fruit Day",
    order: 11,
    isFeatured: false,
  },
  {
    id: "gallery-fruit-02",
    title: "Fruit Day — Team in Green",
    alt: "BALITECH Culture Day and Prize Distribution — team in green shirts",
    src: "/baliCulture_Day/fruit-day/fruit-day-02.png",
    kind: "image",
    section: "gallery",
    category: "Fruit Day",
    order: 12,
    isFeatured: false,
  },
  {
    id: "gallery-fruit-03",
    title: "Fruit Day — Summer Festivities",
    alt: "BALITECH Culture Day and Prize Distribution — employees at summer festivities",
    src: "/baliCulture_Day/fruit-day/fruit-day-03.png",
    kind: "image",
    section: "gallery",
    category: "Fruit Day",
    order: 13,
    isFeatured: false,
  },
  {
    id: "gallery-fruit-04",
    title: "Fruit Day — Photo Frames",
    alt: "BALITECH Culture Day and Prize Distribution — team with fruit-themed photo frames",
    src: "/baliCulture_Day/fruit-day/fruit-day-04.png",
    kind: "image",
    section: "gallery",
    category: "Fruit Day",
    order: 14,
    isFeatured: false,
  },
  {
    id: "gallery-fruit-05",
    title: "Fruit Day — Award Ceremony",
    alt: "BALITECH Culture Day and Prize Distribution — prize distribution ceremony",
    src: "/baliCulture_Day/fruit-day/fruit-day-05.png",
    kind: "image",
    section: "gallery",
    category: "Fruit Day",
    order: 15,
    isFeatured: false,
  },
  {
    id: "gallery-fruit-06",
    title: "Fruit Day — Hello Summer",
    alt: "BALITECH Culture Day and Prize Distribution — team photo with Hello Summer sign",
    src: "/baliCulture_Day/fruit-day/fruit-day-06.png",
    kind: "image",
    section: "gallery",
    category: "Fruit Day",
    order: 16,
    isFeatured: false,
  },
  {
    id: "gallery-fruit-07",
    title: "Fruit Day — Celebration Highlights",
    alt: "BALITECH Culture Day and Prize Distribution — summer celebration highlights",
    src: "/baliCulture_Day/fruit-day/fruit-day-07.png",
    kind: "image",
    section: "gallery",
    category: "Fruit Day",
    order: 17,
    isFeatured: false,
  },
  {
    id: "gallery-fruit-08",
    title: "Fruit Day at BALITECH",
    alt: "BALITECH Culture Day and Prize Distribution — office celebration collage",
    src: "/baliCulture_Day/fruit-day/fruit-day-08.png",
    kind: "image",
    section: "gallery",
    category: "Fruit Day",
    order: 18,
    isFeatured: true,
  },
  {
    id: "gallery-fruit-09",
    title: "Fruit Day — Happy Summer",
    alt: "BALITECH Culture Day and Prize Distribution — Happy Summer team celebration",
    src: "/baliCulture_Day/fruit-day/fruit-day-09.png",
    kind: "image",
    section: "gallery",
    category: "Fruit Day",
    order: 19,
    isFeatured: false,
  },
  {
    id: "gallery-fruit-10",
    title: "Fruit Day — Canvas Painting",
    alt: "BALITECH Culture Day and Prize Distribution — canvas painting activity",
    src: "/baliCulture_Day/fruit-day/fruit-day-10.png",
    kind: "image",
    section: "gallery",
    category: "Fruit Day",
    order: 20,
    isFeatured: false,
  },
  {
    id: "hero-1",
    title: "BALITECH Team",
    alt: "BALITECH team group photo in the forest",
    src: "/hero/hero-team-forest-group.webp",
    kind: "image",
    section: "hero",
    category: "Team",
    order: 1,
    isFeatured: true,
  },
  {
    id: "about-1",
    title: "Culture Day and Prize Distribution — Team Celebration",
    alt: "BALITECH Culture Day and Prize Distribution — team celebration",
    src: "/baliCulture_Day/WhatsApp%20Image%202026-05-11%20at%2012.03.23%20PM%20(1).jpeg",
    kind: "image",
    section: "about-collage",
    category: "Events",
    order: 1,
    isFeatured: true,
  },
  {
    id: "about-2",
    title: "Culture Day and Prize Distribution — Office Festivities",
    alt: "BALITECH Culture Day and Prize Distribution — office festivities",
    src: "/baliCulture_Day/WhatsApp%20Image%202026-05-11%20at%2012.03.24%20PM.jpeg",
    kind: "image",
    section: "about-collage",
    category: "Events",
    order: 2,
    isFeatured: false,
  },
  {
    id: "about-3",
    title: "Culture Day and Prize Distribution — Top Performer",
    alt: "BALITECH Culture Day and Prize Distribution — top performer award",
    src: "/baliCulture_Day/WhatsApp%20Image%202026-05-11%20at%2012.03.25%20PM.jpeg",
    kind: "image",
    section: "about-collage",
    category: "Awards",
    order: 3,
    isFeatured: false,
  },
  {
    id: "about-4",
    title: "Culture Day and Prize Distribution — Cultural Event",
    alt: "BALITECH Culture Day and Prize Distribution — cultural event",
    src: "/baliCulture_Day/WhatsApp%20Image%202026-05-11%20at%2012.03.33%20PM.jpeg",
    kind: "image",
    section: "about-collage",
    category: "Events",
    order: 4,
    isFeatured: false,
  },
  {
    id: "about-5",
    title: "Culture Day and Prize Distribution — Team Gathering",
    alt: "BALITECH Culture Day and Prize Distribution — team gathering",
    src: "/baliCulture_Day/WhatsApp%20Image%202026-05-11%20at%2012.03.34%20PM.jpeg",
    kind: "image",
    section: "about-collage",
    category: "Team",
    order: 5,
    isFeatured: false,
  },
  {
    id: "about-6",
    title: "Culture Day and Prize Distribution — Celebration Highlights",
    alt: "BALITECH Culture Day and Prize Distribution — celebration highlights",
    src: "/baliCulture_Day/WhatsApp%20Image%202026-05-11%20at%2012.03.34%20PM%20(1).jpeg",
    kind: "image",
    section: "about-collage",
    category: "Events",
    order: 6,
    isFeatured: false,
  },
  {
    id: "about-7",
    title: "Culture Day and Prize Distribution — Team Culture",
    alt: "BALITECH Culture Day and Prize Distribution — team culture",
    src: "/baliCulture_Day/WhatsApp%20Image%202026-05-11%20at%2012.03.34%20PM%20(2).jpeg",
    kind: "image",
    section: "about-collage",
    category: "Team",
    order: 7,
    isFeatured: false,
  },
  {
    id: "about-8",
    title: "Culture Day and Prize Distribution — Summer Celebration",
    alt: "BALITECH Culture Day and Prize Distribution — team at summer celebration backdrop",
    src: "/baliCulture_Day/fruit-day/fruit-day-01.png",
    kind: "image",
    section: "about-collage",
    category: "Events",
    order: 8,
    isFeatured: false,
  },
  {
    id: "about-9",
    title: "Culture Day and Prize Distribution — Team in Green",
    alt: "BALITECH Culture Day and Prize Distribution — team in green shirts",
    src: "/baliCulture_Day/fruit-day/fruit-day-02.png",
    kind: "image",
    section: "about-collage",
    category: "Events",
    order: 9,
    isFeatured: false,
  },
  {
    id: "about-10",
    title: "Culture Day and Prize Distribution — Summer Festivities",
    alt: "BALITECH Culture Day and Prize Distribution — employees at summer festivities",
    src: "/baliCulture_Day/fruit-day/fruit-day-03.png",
    kind: "image",
    section: "about-collage",
    category: "Events",
    order: 10,
    isFeatured: false,
  },
  {
    id: "about-11",
    title: "Culture Day and Prize Distribution — Photo Frames",
    alt: "BALITECH Culture Day and Prize Distribution — team with fruit-themed photo frames",
    src: "/baliCulture_Day/fruit-day/fruit-day-04.png",
    kind: "image",
    section: "about-collage",
    category: "Events",
    order: 11,
    isFeatured: false,
  },
  {
    id: "about-12",
    title: "Culture Day and Prize Distribution — Award Ceremony",
    alt: "BALITECH Culture Day and Prize Distribution — prize distribution ceremony",
    src: "/baliCulture_Day/fruit-day/fruit-day-05.png",
    kind: "image",
    section: "about-collage",
    category: "Awards",
    order: 12,
    isFeatured: false,
  },
  {
    id: "about-13",
    title: "Culture Day and Prize Distribution — Hello Summer",
    alt: "BALITECH Culture Day and Prize Distribution — team photo with Hello Summer sign",
    src: "/baliCulture_Day/fruit-day/fruit-day-06.png",
    kind: "image",
    section: "about-collage",
    category: "Events",
    order: 13,
    isFeatured: false,
  },
  {
    id: "about-14",
    title: "Culture Day and Prize Distribution — Celebration Highlights",
    alt: "BALITECH Culture Day and Prize Distribution — summer celebration highlights",
    src: "/baliCulture_Day/fruit-day/fruit-day-07.png",
    kind: "image",
    section: "about-collage",
    category: "Events",
    order: 14,
    isFeatured: false,
  },
  {
    id: "about-15",
    title: "Culture Day and Prize Distribution",
    alt: "BALITECH Culture Day and Prize Distribution — office celebration collage",
    src: "/baliCulture_Day/fruit-day/fruit-day-08.png",
    kind: "image",
    section: "about-collage",
    category: "Events",
    order: 15,
    isFeatured: false,
  },
  {
    id: "about-16",
    title: "Culture Day and Prize Distribution — Happy Summer",
    alt: "BALITECH Culture Day and Prize Distribution — Happy Summer team celebration",
    src: "/baliCulture_Day/fruit-day/fruit-day-09.png",
    kind: "image",
    section: "about-collage",
    category: "Events",
    order: 16,
    isFeatured: false,
  },
  {
    id: "about-17",
    title: "Culture Day and Prize Distribution — Canvas Painting",
    alt: "BALITECH Culture Day and Prize Distribution — canvas painting activity",
    src: "/baliCulture_Day/fruit-day/fruit-day-10.png",
    kind: "image",
    section: "about-collage",
    category: "Events",
    order: 17,
    isFeatured: false,
  },
  ...toAcaSelfVerifierMediaItems(),
];
