export type PublicMediaItem = {
  id: string;
  title: string;
  alt: string | null;
  src: string;
  kind: string;
  section: string;
  category: string;
  order: number;
  isFeatured: boolean;
};

export const fallbackMediaItems: PublicMediaItem[] = [
  {
    id: "workspace-1",
    title: "Main Office Floor",
    alt: "BALITECH office — main workspace and team floor",
    src: "/balitech_office/DSC03829.JPG",
    kind: "image",
    section: "workspace",
    category: "Office",
    order: 1,
    isFeatured: true,
  },
  {
    id: "workspace-2",
    title: "Operations Center",
    alt: "BALITECH office — operations and call center area",
    src: "/balitech_office/DSC03814.JPG",
    kind: "image",
    section: "workspace",
    category: "Office",
    order: 2,
    isFeatured: false,
  },
  {
    id: "workspace-3",
    title: "Team Workstations",
    alt: "BALITECH office — team workstations",
    src: "/balitech_office/DSC03811.JPG",
    kind: "image",
    section: "workspace",
    category: "Office",
    order: 3,
    isFeatured: false,
  },
  {
    id: "video-serena",
    title: "ACA Serena Breakfast",
    alt: "ACA Serena Breakfast event video",
    src: "/Serena%20Breakfast/ACA%20Serena%20Breakfast.mp4",
    kind: "video",
    section: "portrait-video",
    category: "Events",
    order: 1,
    isFeatured: false,
  },
  {
    id: "video-transition",
    title: "Transition Video",
    alt: "BALITECH transition video",
    src: "/transition%20video/Transition%20Video1.mp4",
    kind: "video",
    section: "portrait-video",
    category: "Events",
    order: 2,
    isFeatured: false,
  },
  {
    id: "video-independence",
    title: "Independence Day Celebration",
    alt: "Independence Day celebration video",
    src: "/independence%20video/Independence%20day%20celeberation.mp4",
    kind: "video",
    section: "portrait-video",
    category: "Events",
    order: 3,
    isFeatured: false,
  },
  {
    id: "video-new-year",
    title: "Balitech New Year",
    alt: "Balitech New Year celebration video",
    src: "/newyear/Balitech%20New%20Year.mp4",
    kind: "video",
    section: "featured-video",
    category: "Events",
    order: 1,
    isFeatured: true,
  },
  {
    id: "events-1",
    title: "Strategic Session",
    alt: "Strategic Session",
    src: "/gallery/gallery-event-1.jpg",
    kind: "image",
    section: "events",
    category: "Events",
    order: 1,
    isFeatured: true,
  },
  {
    id: "events-2",
    title: "Leadership Briefing",
    alt: "Leadership Briefing",
    src: "/gallery/gallery-team-group-night.png",
    kind: "image",
    section: "events",
    category: "Events",
    order: 2,
    isFeatured: false,
  },
  {
    id: "events-3",
    title: "Balitech Commercial Office",
    alt: "Balitech Commercial Office",
    src: "/gallery/gallery-event-3.png",
    kind: "image",
    section: "events",
    category: "Office",
    order: 3,
    isFeatured: false,
  },
  {
    id: "events-4",
    title: "Annual Celebrations",
    alt: "Annual Celebrations",
    src: "/gallery/gallery-event-4.jpg",
    kind: "image",
    section: "events",
    category: "Events",
    order: 4,
    isFeatured: false,
  },
  {
    id: "events-5",
    title: "Top Performers Recognition",
    alt: "Top Performers Recognition",
    src: "/gallery/gallery-event-5.png",
    kind: "image",
    section: "events",
    category: "Awards",
    order: 5,
    isFeatured: false,
  },
  {
    id: "gallery-1",
    title: "Annual Dinner 2025",
    alt: "Annual Dinner 2025",
    src: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=800&q=80",
    kind: "image",
    section: "gallery",
    category: "Events",
    order: 1,
    isFeatured: false,
  },
  {
    id: "gallery-2",
    title: "Employee Awards Night",
    alt: "Employee Awards Night",
    src: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=600&q=80",
    kind: "image",
    section: "gallery",
    category: "Awards",
    order: 2,
    isFeatured: false,
  },
  {
    id: "gallery-3",
    title: "Main Office Floor",
    alt: "Main Office Floor",
    src: "/balitech_office/DSC03829.JPG",
    kind: "image",
    section: "gallery",
    category: "Office",
    order: 3,
    isFeatured: false,
  },
];
