export type PublicMediaItem = {
  id: string;
  title: string;
  alt: string | null;
  src: string;
  kind: string;
  section: string;
  category: string;
  order: number;
  isFeatured: boolean;
};

export const fallbackMediaItems: PublicMediaItem[] = [
  {
    id: "award-1",
    title: "iPhone & Certificate Award",
    alt: "BALITECH employee receiving iPhone and certificate award",
    src: "/awards/award-iphone-certificate.png",
    kind: "image",
    section: "awards",
    category: "Awards",
    order: 1,
    isFeatured: true,
  },
  {
    id: "award-honda",
    title: "Honda CG 125 Top Performer",
    alt: "BALITECH top performer Honda CG 125 motorcycle presentation",
    src: "/awards/award-honda-motorcycle-presentation.jpg",
    kind: "image",
    section: "awards",
    category: "Awards",
    order: 2,
    isFeatured: false,
  },
  {
    id: "award-emporio",
    title: "Top Performer Emporio Armani Gift",
    alt: "BALITECH top performer receiving Emporio Armani gift",
    src: "/awards/award-emporio-armani-gift.jpg",
    kind: "image",
    section: "awards",
    category: "Awards",
    order: 3,
    isFeatured: false,
  },
  {
    id: "bonus-tommy",
    title: "Tommy Espinoza — Med Alert Bonus Achiever",
    alt: "Tommy Espinoza Med Alert Bonus Achiever — earned 166,500",
    src: "/awards/bonus-tommy-espinoza.png",
    kind: "image",
    section: "bonus-achievers",
    category: "Awards",
    order: 1,
    isFeatured: false,
  },
  {
    id: "bonus-ronnie",
    title: "Ronnie Adams — Med Alert Bonus Achiever",
    alt: "Ronnie Adams Med Alert Bonus Achiever — earned 251,500",
    src: "/awards/bonus-ronnie-adams.png",
    kind: "image",
    section: "bonus-achievers",
    category: "Awards",
    order: 2,
    isFeatured: false,
  },
  {
    id: "bonus-ken",
    title: "Ken Lee — Med Alert Bonus Achiever",
    alt: "Ken Lee Med Alert Bonus Achiever — earned 176,500",
    src: "/awards/bonus-ken-lee.png",
    kind: "image",
    section: "bonus-achievers",
    category: "Awards",
    order: 3,
    isFeatured: false,
  },
  {
    id: "promo-mohsin",
    title: "Mohsin Nazir — Verifier to Team Lead",
    alt: "Mohsin Nazir promoted from Verifier to Team Lead at BALITECH",
    src: "/awards/promotion-mohsin-nazir.png",
    kind: "image",
    section: "promotions",
    category: "Team",
    order: 1,
    isFeatured: false,
  },
  {
    id: "promo-shad",
    title: "Shad Azam — Verifier to Team Lead",
    alt: "Shad Azam promoted from Verifier to Team Lead at BALITECH",
    src: "/awards/promotion-shad-azam.png",
    kind: "image",
    section: "promotions",
    category: "Team",
    order: 2,
    isFeatured: false,
  },
  {
    id: "promo-haris",
    title: "Haris Zaheer — Associate Manager",
    alt: "Haris Zaheer promoted to Associate Manager at BALITECH",
    src: "/awards/promotion-haris-zaheer.png",
    kind: "image",
    section: "promotions",
    category: "Team",
    order: 3,
    isFeatured: false,
  },
  {
    id: "promo-zimmel",
    title: "Zimmel Shahid — Retention Manager",
    alt: "Zimmel Shahid promoted from Closer to Retention Manager on Med Alert Campaign",
    src: "/awards/promotion-zimmel-shahid.png",
    kind: "image",
    section: "promotions",
    category: "Team",
    order: 4,
    isFeatured: false,
  },
  {
    id: "workspace-1",
    title: "Main Office Floor",
    alt: "BALITECH office — main workspace and team floor",
    src: "/balitech_office/DSC03829.JPG",
    kind: "image",
    section: "workspace",
    category: "Office",
    order: 1,
    isFeatured: true,
  },
  {
    id: "workspace-2",
    title: "Operations Center",
    alt: "BALITECH office — operations and call center area",
    src: "/balitech_office/DSC03814.JPG",
    kind: "image",
    section: "workspace",
    category: "Office",
    order: 2,
    isFeatured: false,
  },
  {
    id: "workspace-3",
    title: "Team Workstations",
    alt: "BALITECH office — team workstations",
    src: "/balitech_office/DSC03811.JPG",
    kind: "image",
    section: "workspace",
    category: "Office",
    order: 3,
    isFeatured: false,
  },
  {
    id: "video-serena",
    title: "ACA Serena Breakfast",
    alt: "ACA Serena Breakfast event video",
    src: "/Serena%20Breakfast/ACA%20Serena%20Breakfast.mp4",
    kind: "video",
    section: "portrait-video",
    category: "Events",
    order: 1,
    isFeatured: false,
  },
  {
    id: "video-transition",
    title: "Transition Video",
    alt: "BALITECH transition video",
    src: "/transition%20video/Transition%20Video1.mp4",
    kind: "video",
    section: "portrait-video",
    category: "Events",
    order: 2,
    isFeatured: false,
  },
  {
    id: "video-independence",
    title: "Independence Day Celebration",
    alt: "Independence Day celebration video",
    src: "/independence%20video/Independence%20day%20celeberation.mp4",
    kind: "video",
    section: "portrait-video",
    category: "Events",
    order: 3,
    isFeatured: false,
  },
  {
    id: "video-new-year",
    title: "Balitech New Year",
    alt: "Balitech New Year celebration video",
    src: "/newyear/Balitech%20New%20Year.mp4",
    kind: "video",
    section: "featured-video",
    category: "Events",
    order: 1,
    isFeatured: true,
  },
  {
    id: "events-1",
    title: "Strategic Session",
    alt: "Strategic Session",
    src: "/gallery/gallery-event-1.jpg",
    kind: "image",
    section: "events",
    category: "Events",
    order: 1,
    isFeatured: true,
  },
  {
    id: "events-2",
    title: "Leadership Briefing",
    alt: "Leadership Briefing",
    src: "/gallery/gallery-team-group-night.png",
    kind: "image",
    section: "events",
    category: "Events",
    order: 2,
    isFeatured: false,
  },
  {
    id: "events-3",
    title: "Balitech Commercial Office",
    alt: "Balitech Commercial Office",
    src: "/gallery/gallery-event-3.png",
    kind: "image",
    section: "events",
    category: "Office",
    order: 3,
    isFeatured: false,
  },
  {
    id: "events-4",
    title: "Annual Celebrations",
    alt: "Annual Celebrations",
    src: "/gallery/gallery-event-4.jpg",
    kind: "image",
    section: "events",
    category: "Events",
    order: 4,
    isFeatured: false,
  },
  {
    id: "events-5",
    title: "Top Performers Recognition",
    alt: "Top Performers Recognition",
    src: "/gallery/gallery-event-5.png",
    kind: "image",
    section: "events",
    category: "Awards",
    order: 5,
    isFeatured: false,
  },
  {
    id: "gallery-1",
    title: "Annual Dinner 2025",
    alt: "Annual Dinner 2025",
    src: "/gallery/gallery-event-1.jpg",
    kind: "image",
    section: "gallery",
    category: "Events",
    order: 1,
    isFeatured: false,
  },
  {
    id: "gallery-2",
    title: "Employee Awards Night",
    alt: "Employee Awards Night",
    src: "/awards/award-certificate-ceremony.png",
    kind: "image",
    section: "gallery",
    category: "Awards",
    order: 2,
    isFeatured: false,
  },
  {
    id: "gallery-3",
    title: "Team Group Night",
    alt: "BALITECH team group photo at night",
    src: "/gallery/gallery-team-group-night.png",
    kind: "image",
    section: "gallery",
    category: "Team",
    order: 3,
    isFeatured: false,
  },
  {
    id: "gallery-4",
    title: "Annual Celebrations",
    alt: "Annual Celebrations",
    src: "/gallery/gallery-event-4.jpg",
    kind: "image",
    section: "gallery",
    category: "Events",
    order: 4,
    isFeatured: false,
  },
  {
    id: "gallery-5",
    title: "Top Performer Ceremony",
    alt: "Top Performer Ceremony",
    src: "/awards/award-honda-motorcycle-presentation.jpg",
    kind: "image",
    section: "gallery",
    category: "Awards",
    order: 5,
    isFeatured: false,
  },
  {
    id: "gallery-6",
    title: "Main Office Floor",
    alt: "Main Office Floor",
    src: "/balitech_office/DSC03829.JPG",
    kind: "image",
    section: "gallery",
    category: "Office",
    order: 6,
    isFeatured: false,
  },
  {
    id: "gallery-7",
    title: "Operations Center",
    alt: "Operations Center",
    src: "/balitech_office/DSC03814.JPG",
    kind: "image",
    section: "gallery",
    category: "Office",
    order: 7,
    isFeatured: false,
  },
  {
    id: "gallery-8",
    title: "Commercial Office Floor",
    alt: "Commercial Office Floor",
    src: "/gallery/gallery-office-workplace-1.jpg",
    kind: "image",
    section: "gallery",
    category: "Office",
    order: 8,
    isFeatured: false,
  },
  {
    id: "gallery-9",
    title: "Commercial Workspaces",
    alt: "Commercial Workspaces",
    src: "/gallery/gallery-office-workplace-2.jpg",
    kind: "image",
    section: "gallery",
    category: "Office",
    order: 9,
    isFeatured: false,
  },
  {
    id: "gallery-10",
    title: "Commercial Operations",
    alt: "Commercial Operations",
    src: "/gallery/gallery-office-workplace-3.jpg",
    kind: "image",
    section: "gallery",
    category: "Office",
    order: 10,
    isFeatured: false,
  },
  {
    id: "hero-1",
    title: "Team Meeting",
    alt: "Bali Tech team meeting discussion",
    src: "/hero/hero-meeting-foreground.jpg",
    kind: "image",
    section: "hero",
    category: "Team",
    order: 1,
    isFeatured: true,
  },
  {
    id: "hero-2",
    title: "Outdoor Team Gathering",
    alt: "Bali Tech team outdoor gathering at night",
    src: "/hero/hero-outdoor-night.jpg",
    kind: "image",
    section: "hero",
    category: "Team",
    order: 2,
    isFeatured: false,
  },
  {
    id: "hero-3",
    title: "Team Group Outdoors",
    alt: "BALITECH team group photo outdoors",
    src: "/hero/hero-team-group-outdoor.jpg",
    kind: "image",
    section: "hero",
    category: "Office",
    order: 3,
    isFeatured: false,
  },
  {
    id: "hero-4",
    title: "Pine View Hotel Team Trip",
    alt: "BALITECH team at Pine View Hotel",
    src: "/hero/hero-pine-view-hotel.jpg",
    kind: "image",
    section: "hero",
    category: "Team",
    order: 4,
    isFeatured: false,
  },
  {
    id: "about-1",
    title: "Bali Culture Day — Team Celebration",
    alt: "BALITECH Bali Culture Day — team celebration",
    src: "/baliCulture_Day/WhatsApp%20Image%202026-05-11%20at%2012.03.23%20PM%20(1).jpeg",
    kind: "image",
    section: "about-collage",
    category: "Events",
    order: 1,
    isFeatured: true,
  },
  {
    id: "about-2",
    title: "Bali Culture Day — Office Festivities",
    alt: "BALITECH Bali Culture Day — office festivities",
    src: "/baliCulture_Day/WhatsApp%20Image%202026-05-11%20at%2012.03.24%20PM.jpeg",
    kind: "image",
    section: "about-collage",
    category: "Events",
    order: 2,
    isFeatured: false,
  },
  {
    id: "about-3",
    title: "Bali Culture Day — Top Performer",
    alt: "BALITECH Bali Culture Day — top performer award",
    src: "/baliCulture_Day/WhatsApp%20Image%202026-05-11%20at%2012.03.25%20PM.jpeg",
    kind: "image",
    section: "about-collage",
    category: "Awards",
    order: 3,
    isFeatured: false,
  },
  {
    id: "about-4",
    title: "Bali Culture Day — Cultural Event",
    alt: "BALITECH Bali Culture Day — cultural event",
    src: "/baliCulture_Day/WhatsApp%20Image%202026-05-11%20at%2012.03.33%20PM.jpeg",
    kind: "image",
    section: "about-collage",
    category: "Events",
    order: 4,
    isFeatured: false,
  },
  {
    id: "about-5",
    title: "Bali Culture Day — Team Gathering",
    alt: "BALITECH Bali Culture Day — team gathering",
    src: "/baliCulture_Day/WhatsApp%20Image%202026-05-11%20at%2012.03.34%20PM.jpeg",
    kind: "image",
    section: "about-collage",
    category: "Team",
    order: 5,
    isFeatured: false,
  },
  {
    id: "about-6",
    title: "Bali Culture Day — Celebration Highlights",
    alt: "BALITECH Bali Culture Day — celebration highlights",
    src: "/baliCulture_Day/WhatsApp%20Image%202026-05-11%20at%2012.03.34%20PM%20(1).jpeg",
    kind: "image",
    section: "about-collage",
    category: "Events",
    order: 6,
    isFeatured: false,
  },
  {
    id: "about-7",
    title: "Bali Culture Day — Team Culture",
    alt: "BALITECH Bali Culture Day — team culture",
    src: "/baliCulture_Day/WhatsApp%20Image%202026-05-11%20at%2012.03.34%20PM%20(2).jpeg",
    kind: "image",
    section: "about-collage",
    category: "Team",
    order: 7,
    isFeatured: false,
  },
];
